spring:
  application:
    name: my-vocabulary
  config:
    import: optional:secrets.yml

  datasource:
    url: jdbc:mysql://localhost:3306/my_vocabulary?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    sql: debug